const assert=require('node:assert/strict');
const {chromium}=require('playwright');
const base=process.env.GROOVESHELF_TEST_URL||'http://127.0.0.1:8080';
(async()=>{const browser=await chromium.launch();try{const page=await browser.newPage();await page.goto(base);await page.locator('#theme-name').waitFor();await page.locator('#search').fill('theme regression');await page.getByRole('button',{name:'Table',exact:true}).click();
for(const theme of ['studio','listening','gallery']){const table=await page.locator('#collection').elementHandle();await page.locator('.theme-picker summary').click();await page.locator(`button[data-theme=${theme}]`).click();assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),theme);
const contrasts=await page.evaluate(()=>{
 const luminance=color=>{const channels=color.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});return channels[0]*.2126+channels[1]*.7152+channels[2]*.0722;};
 return ['#wishlist-open','.nav-item.active','#add','#search','.theme-picker summary'].map(selector=>{
  const element=document.querySelector(selector);let parent=element,background;
  while(parent){background=getComputedStyle(parent).backgroundColor;if(background!=='rgba(0, 0, 0, 0)'&&background!=='transparent')break;parent=parent.parentElement;}
  const a=luminance(getComputedStyle(element).color),b=luminance(background);
  return {selector,ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05)};
 });
});
for(const contrast of contrasts)assert(contrast.ratio>=4.5,`${theme} ${contrast.selector} text contrast: ${contrast.ratio}`);
assert.equal(await page.locator('#search').inputValue(),'theme regression');assert.equal(await page.getByRole('button',{name:'Table',exact:true}).getAttribute('aria-pressed'),'true');assert(await page.evaluate(el=>el===document.querySelector('#collection'),table));await page.reload();assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),theme);await page.locator('#search').fill('theme regression');await page.getByRole('button',{name:'Table',exact:true}).click();}
await page.locator('#add').click();await page.locator('#record-form [name=artist]').fill('Unsaved input');await page.evaluate(()=>document.querySelector('button[data-theme=studio]').click());assert.equal(await page.locator('#record-form [name=artist]').inputValue(),'Unsaved input');await page.keyboard.press('Escape');await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.querySelector('#app-navigation').inert);assert(await page.locator('#app-navigation').evaluate(el=>el.inert));await page.locator('#nav-toggle').click();assert.equal(await page.locator('#nav-toggle').getAttribute('aria-expanded'),'true');assert(await page.locator('#app-main').evaluate(el=>el.inert));await page.keyboard.press('Escape');assert.equal(await page.locator('#nav-toggle').getAttribute('aria-expanded'),'false');assert(await page.locator('#nav-toggle').evaluate(el=>el===document.activeElement));await page.locator('#nav-toggle').click();await page.locator('#settings-open').click();assert(await page.locator('#settings').evaluate(el=>el.open));assert(!await page.locator('#app-main').evaluate(el=>el.inert));await page.keyboard.press('Escape');for(const size of [{width:390,height:844},{width:800,height:480},{width:1024,height:600}]){await page.setViewportSize(size);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}console.log('Appearance passed: three themes, persistence, retained controls and input, responsive navigation, focus and Pi layout.');}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
