const assert=require('node:assert/strict');
const {chromium}=require('playwright');
const {openNavigation}=require('./navigation.cjs');
const base=process.env.GROOVESHELF_TEST_URL||'http://127.0.0.1:8080';
(async()=>{
  const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});const ids=[];const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  const get=async id=>(await page.request.get(`${base}/api/records/${id}`)).json();
  async function open(){await openNavigation(page);await page.locator('#bulk-open').click();await page.locator('#bulk-reload').waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('#bulk-reload').disabled);}
  async function selectMove(){await page.locator('#bulk-filter').fill('Move Album');await page.locator('#bulk-select').click();await page.getByText('2 selected · 2 matching',{exact:true}).waitFor();}
  try {
    await page.goto(base);await open();await page.getByText('Your collection is empty. Add records before using bulk edit.').waitFor();await page.locator('#bulk-close').click();
    for(let i=0;i<3;i++){
      const result=await page.request.post(base+'/api/records',{data:{inventory_number:`LP-${88211+i}`,artist:'Bulk <Artist>',title:i<2?'Move Album':'Leave Album',storage_location:'Shelf A',rating:2,media_condition:'VG',sleeve_condition:'Generic',notes:'Individual notes'}});assert(result.ok());ids.push((await result.json()).id);
    }
    await page.reload();await open();await selectMove();await page.locator('#bulk-filter').fill('LP-88213');await page.locator('#bulk-records input').check();await page.getByText('3 selected · 1 matching',{exact:true}).waitFor();await page.locator('#bulk-filter').fill('not found');await page.getByText('3 selected · 0 matching',{exact:true}).waitFor();await page.locator('#bulk-review').click();await page.getByText('Choose at least one field to change.',{exact:true}).waitFor();await page.locator('#bulk-cancel').click();assert.equal((await get(ids[0])).rating,2);
    await open();assert.equal(await page.locator('#bulk-form [name=rating]').inputValue(),'__keep');await selectMove();await page.locator('#bulk-location-change').check();await page.locator('#bulk-form [name=storage_location]').fill('Office <Shelf B>');await page.locator('#bulk-form [name=rating]').selectOption('5');await page.locator('#bulk-form [name=media_condition]').selectOption('NM');await page.locator('#bulk-form [name=favorite]').selectOption('true');await page.locator('#bulk-review').click();await page.getByText('Update 2 copies',{exact:true}).waitFor();assert.equal(await page.locator('#bulk-review-records li').count(),2);assert.equal(await page.locator('#bulk-changes').getByText('Storage location: Office <Shelf B>',{exact:true}).count(),1);assert.equal(await page.locator('#bulk-editor script').count(),0);
    await page.locator('#bulk-back').click();assert.equal(await page.locator('#bulk-form [name=rating]').inputValue(),'5');assert.equal(await page.locator('#bulk-records input:checked').count(),2);await page.locator('#bulk-review').click();await page.keyboard.press('Escape');await page.locator('#bulk-editor').waitFor({state:'hidden'});assert.equal((await get(ids[0])).storage_location,'Shelf A');
    await open();await selectMove();await page.locator('#bulk-location-change').check();await page.locator('#bulk-form [name=storage_location]').fill('Office <Shelf B>');await page.locator('#bulk-form [name=rating]').selectOption('5');await page.locator('#bulk-form [name=media_condition]').selectOption('NM');await page.locator('#bulk-form [name=favorite]').selectOption('true');await page.locator('#bulk-review').click();
    for(const theme of ['gallery','studio','listening']){await page.evaluate(theme=>document.querySelector(`button[data-theme=${theme}]`).click(),theme);await page.screenshot({path:`/tmp/grooveshelf-bulk-${theme}-mobile.png`});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
    let release;const gate=new Promise(resolve=>release=resolve);let requests=0;
    await page.route('**/api/records/bulk-personal',async route=>{requests++;await gate;await route.continue();});await page.locator('#bulk-apply').click();await page.waitForFunction(()=>document.querySelector('#bulk-apply').disabled);await page.keyboard.press('Escape');assert(await page.locator('#bulk-editor').evaluate(el=>el.open));release();await page.locator('#bulk-editor').waitFor({state:'hidden'});await page.getByText('Updated 2 records.',{exact:true}).waitFor();assert.equal(requests,1);await page.unroute('**/api/records/bulk-personal');
    for(const id of ids.slice(0,2)){const record=await get(id);assert.equal(record.rating,5);assert.equal(record.media_condition,'NM');assert.equal(record.favorite,true);assert.equal(record.storage_location,'Office <Shelf B>');assert.equal(record.sleeve_condition,'Generic');assert.equal(record.notes,'Individual notes');}assert.equal((await get(ids[2])).rating,2);
    await open();await selectMove();await page.locator('#bulk-location-change').check();await page.locator('#bulk-form [name=rating]').selectOption('');await page.locator('#bulk-form [name=media_condition]').selectOption('');await page.locator('#bulk-form [name=sleeve_condition]').selectOption('');await page.locator('#bulk-form [name=favorite]').selectOption('false');await page.locator('#bulk-review').click();await page.getByText('Rating: Clear rating',{exact:true}).waitFor();await page.locator('#bulk-apply').click();await page.locator('#bulk-editor').waitFor({state:'hidden'});const cleared=await get(ids[0]);assert.equal(cleared.rating,null);assert.equal(cleared.media_condition,null);assert.equal(cleared.sleeve_condition,null);assert.equal(cleared.storage_location,'');assert.equal(cleared.favorite,false);
    await open();await selectMove();await page.locator('#bulk-form [name=rating]').selectOption('3');await page.locator('#bulk-review').click();await page.request.delete(`${base}/api/records/${ids[1]}`);await page.locator('#bulk-apply').click();await page.getByText('Some selected records no longer exist. Reload the records and review your selection.',{exact:true}).waitFor();assert.equal((await get(ids[0])).rating,null);await page.locator('#bulk-back').click();await page.locator('#bulk-reload').click();await page.getByText('1 selected · 1 matching',{exact:true}).waitFor();await page.locator('#bulk-review').click();await page.getByText('Update 1 copy',{exact:true}).waitFor();await page.locator('#bulk-apply').click();await page.locator('#bulk-editor').waitFor({state:'hidden'});assert.equal((await get(ids[0])).rating,3);
    await page.reload();await page.setViewportSize({width:1280,height:900});await open();await page.locator('#bulk-filter').fill('Shelf A');await page.locator('#bulk-select').click();await page.getByText('1 selected · 1 matching',{exact:true}).waitFor();await page.locator('#bulk-clear').click();assert(await page.locator('#bulk-review').isDisabled());assert.deepEqual(errors,[]);
    console.log('Bulk edit passed: selection/filter, draft/review/cancel, omitted fields, clear values, atomic conflicts, reload, submission guard, themes and mobile layout.');
  } finally {for(const id of ids)await page.request.delete(`${base}/api/records/${id}`);await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
