const assert=require('node:assert/strict');const {chromium}=require('playwright');const base=process.env.GROOVESHELF_TEST_URL||'http://127.0.0.1:8080';
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});const ids=[];const errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto(base);await page.locator('#discover-open').click();await page.getByText('Your collection is empty. Add a record to get suggestions.').waitFor();await page.locator('#discover-close').click();
 for(const [inventory_number,title] of [['LP-88661','First suggestion'],['LP-88662','Second suggestion']]){const r=await page.request.post(base+'/api/records',{data:{inventory_number,artist:'Discovery Artist',title}});assert(r.ok());ids.push((await r.json()).id);}
 await page.locator('#discover-open').click();await page.getByText('2 eligible copies.').waitFor();const first=await page.locator('#discover-result h3').textContent();await page.locator('#discover-another').click();await page.getByText('2 eligible copies.').waitFor();assert.notEqual(await page.locator('#discover-result h3').textContent(),first);
 await page.locator('#discover-mode').selectOption('never');await page.getByText('2 eligible copies.').waitFor();
 await page.screenshot({path:'/tmp/grooveshelf-discovery-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#discover-details').click();await page.locator('#details').waitFor({state:'visible'});assert((await (await page.request.get(base+'/api/records')).json()).every(r=>r.play_count===0));await page.getByRole('button',{name:'Close details'}).click();
 for(const id of ids)await page.request.post(`${base}/api/records/${id}/plays`,{data:{played_at:new Date().toISOString()}});
 await page.locator('#discover-open').click();await page.getByText('No records match this selection. Choose another group.').waitFor();await page.locator('#discover-mode').selectOption('recent');await page.getByText('No records match this selection. Choose another group.').waitFor();await page.locator('#discover-mode').selectOption('least');await page.getByText('2 eligible copies.').waitFor();
 assert.deepEqual(errors,[]);console.log('Discovery browser flow passed: empty collection, another suggestion, modes, empty group, details, no play creation and mobile layout.');
 }finally{for(const id of ids)await page.request.delete(base+'/api/records/'+id);await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
