const assert=require('node:assert/strict');const fs=require('node:fs');const {chromium}=require('playwright');const base=process.env.GROOVESHELF_TEST_URL||'http://127.0.0.1:8080';
(async()=>{
 const {labelDocument}=await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(require('node:path').join(__dirname,'../labels.js'),'utf8')).toString('base64'));
 const values={paper:'A4',columns:3,width:63.5,height:38.1,margin_x:7,margin_y:15,gap_x:2,gap_y:0,skip:0};
 const numbers=Array.from({length:22},(_,n)=>`LP-${String(n+1).padStart(5,'0')}`);
 const document=labelDocument(numbers,values,value=>value);assert.equal(document.capacity,21);assert.equal(document.pages,2);assert.equal(labelDocument(numbers.slice(0,21),{...values,skip:1},value=>value).pages,2);
 assert.throws(()=>labelDocument(numbers,{...values,width:100},value=>value),/page width/);assert.throws(()=>labelDocument(numbers,{...values,height:280},value=>value),/page/);assert.throws(()=>labelDocument(numbers,{...values,skip:21},value=>value),/Used labels/);assert.throws(()=>labelDocument([],values,value=>value),/Select/);assert.throws(()=>labelDocument(['invalid'],values,value=>value),/invalid/);
 assert.equal(labelDocument(numbers,{...values,paper:'Letter'},value=>value).rows,6);
 const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});const ids=[];const errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.goto(base);await page.locator('#labels-open').click();await page.getByText('Your collection is empty. Add records before printing labels.').waitFor();await page.locator('#labels-close').click();
  for(const inventory_number of ['LP-88441','LP-88442']){const response=await page.request.post(base+'/api/records',{data:{inventory_number,artist:'Label Artist',title:'Label Album'}});assert(response.ok());ids.push((await response.json()).id);}
  await page.locator('#labels-open').click();await page.getByText('0 selected · 2 visible').waitFor();await page.locator('#labels-filter').fill('88441');await page.locator('#labels-select').click();await page.getByText('1 selected · 1 visible').waitFor();await page.locator('#labels-filter').fill('');await page.locator('#labels-select').click();await page.getByText('2 selected · 2 visible').waitFor();
  await page.locator('#labels-form [name=skip]').fill('1');await page.getByRole('button',{name:'Build preview'}).click();await page.locator('#labels-output').waitFor({state:'visible'});const frame=page.frameLocator('#labels-preview');await frame.getByText('LP-88441',{exact:true}).waitFor();assert.equal(await frame.locator('.label').count(),3);assert.equal(await frame.locator('.label').first().textContent(),'');
  await page.locator('#labels-preview').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/grooveshelf-labels-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  const preview=page.frames().find(f=>f.parentFrame());await preview.evaluate(()=>{window.print=()=>{window.printCalled=true;};});await page.locator('#labels-print').click();assert(await preview.evaluate(()=>window.printCalled));
  const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#labels-download').click()]);assert.equal(download.suggestedFilename(),'grooveshelf-labels.html');const path=await download.path();const html=fs.readFileSync(path,'utf8');assert(html.includes('LP-88441'));assert(html.includes('@page{size:A4;margin:0}'));assert(!html.includes('<script'));
  await page.locator('#labels-form [name=width]').fill('100');assert(await page.locator('#labels-output').isHidden());await page.getByRole('button',{name:'Build preview'}).click();await page.getByText('The columns, gaps and margins do not fit this page width.').waitFor();await page.locator('#labels-form [name=width]').fill('63.5');await page.locator('#labels-clear').click();await page.getByRole('button',{name:'Build preview'}).click();await page.getByText('Select at least one record.').waitFor();
  assert.deepEqual(errors,[]);console.log('Labels browser flow passed: page geometry, pagination, selection/filter, used slots, preview, print, standalone download, invalidation, errors and mobile layout.');
 }finally{for(const id of ids)await page.request.delete(base+'/api/records/'+id);await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
