const assert=require('node:assert/strict');const {chromium}=require('playwright');const base=process.env.GROOVESHELF_TEST_URL||'http://127.0.0.1:8080';
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});let id;const errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto(base);await page.locator('#add').click();await page.locator('#record-form [name=inventory_number]').fill('LP-88331');await page.locator('#record-form [name=artist]').fill('Location Artist');await page.locator('#record-form [name=title]').fill('Location Album');await page.locator('#record-form [name=storage_location]').fill('Living room · Shelf B');await page.locator('#save').click();await page.locator('#details').waitFor({state:'visible'});id=page.url().split('#record/')[1];await page.locator('#personal-summary').getByText('Living room · Shelf B',{exact:true}).waitFor();
 await page.locator('#edit-personal').click();await page.locator('#personal-form [name=storage_location]').fill('Canceled location');await page.locator('#personal-cancel').click();assert.equal((await(await page.request.get(base+'/api/records/'+id)).json()).storage_location,'Living room · Shelf B');
 await page.locator('#edit-personal').click();await page.locator('#personal-form [name=storage_location]').fill('Office <Shelf C>');await page.locator('#personal-save').click();await page.locator('#personal-editor').waitFor({state:'hidden'});await page.locator('#personal-summary').getByText('Office <Shelf C>',{exact:true}).waitFor();await page.locator('#close-details').click();
 await page.getByRole('button',{name:'Grid',exact:true}).click();await page.locator('#collection').getByText('Office <Shelf C>',{exact:true}).waitFor();await page.getByRole('searchbox',{name:'Search collection'}).fill('SHELF C');await page.getByText('1 record',{exact:true}).waitFor();await page.getByRole('button',{name:'Table',exact:true}).click();await page.locator('#collection td').getByText('Office <Shelf C>',{exact:true}).waitFor();await page.locator('#collection').getByRole('button',{name:'Location Album',exact:true}).click();await page.locator('#details').waitFor({state:'visible'});await page.reload();await page.locator('#personal-summary').getByText('Office <Shelf C>',{exact:true}).waitFor();
 await page.screenshot({path:'/tmp/grooveshelf-locations-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#edit').click();assert.equal(await page.locator('#record-form [name=storage_location]').inputValue(),'Office <Shelf C>');await page.locator('#record-form [name=title]').fill('Edited Location Album');await page.locator('#save').click();await page.locator('#editor').waitFor({state:'hidden'});assert.equal((await(await page.request.get(base+'/api/records/'+id)).json()).storage_location,'Office <Shelf C>');
 await page.locator('#edit-personal').click();await page.locator('#personal-form [name=storage_location]').fill('');await page.locator('#personal-save').click();await page.locator('#personal-editor').waitFor({state:'hidden'});await page.locator('#personal-summary').getByText('Not added',{exact:true}).waitFor();assert.deepEqual(errors,[]);console.log('Location browser flow passed: add, cancel, edit, escaped display, grid/table/search, reload, full editing, clear and mobile layout.');
 }finally{if(id)await page.request.delete(base+'/api/records/'+id);await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
