const assert=require('node:assert/strict');const fs=require('node:fs');const {pathToFileURL}=require('node:url');const {join}=require('node:path');const {chromium}=require('playwright');const jsQR=require('jsqr');const {PNG}=require('pngjs');const {openNavigation}=require('./navigation.cjs');
const base=process.env.GROOVESHELF_TEST_URL||'http://127.0.0.1:8080';
async function decode(locator){const png=PNG.sync.read(await locator.screenshot());const code=jsQR(new Uint8ClampedArray(png.data),png.width,png.height);assert(code,'An independent decoder must recognize the rendered QR');return code.data;}
(async()=>{
 const {collectionOrigin,recordLink,recordQR}=await import(pathToFileURL(join(__dirname,'../qr.js')).href);
 const {labelDocument}=await import(pathToFileURL(join(__dirname,'../labels.js')).href);
 assert.equal(collectionOrigin('http://grooveshelf.local:8080/'),'http://grooveshelf.local:8080');assert.equal(collectionOrigin('https://[::1]:8443'),'https://[::1]:8443');
 for(const value of ['javascript:alert(1)','file:///etc/passwd','http://user:secret@example.test','http://example.test/path','http://example.test/?token=secret','http://example.test/#fragment','not an address'])assert.throws(()=>collectionOrigin(value));
 assert.throws(()=>recordLink('<script>','http://example.test'));assert.equal(recordQR('copy-123','http://example.test').url,'http://example.test/#record/copy-123');
 const config={paper:'A4',columns:3,width:63.5,height:38.1,margin_x:7,margin_y:15,gap_x:2,gap_y:0,skip:1,qr:true,qr_origin:base};const copies=[{id:'copy-123',inventory_number:'LP-88551'}];
 assert.throws(()=>labelDocument(['LP-88551'],{...config,height:20},v=>v,copies),/at least 30/);assert.throws(()=>labelDocument(['LP-88551'],config,v=>v,[]),/Reload/);assert.throws(()=>labelDocument(['LP-88551'],{...config,qr_origin:'https://'+'a'.repeat(280)+'.test'},v=>v,copies),/too dense/);assert(!labelDocument(['LP-88551'],{...config,qr:false},v=>v).html.includes('<svg'));
 const browser=await chromium.launch();const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,reducedMotion:'reduce'});const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));let id;const external=[];page.on('request',request=>{if(!request.url().startsWith(base)&&!request.url().startsWith('data:')&&!request.url().startsWith('blob:')&&!request.url().startsWith('about:'))external.push(request.url());});
 try{
  const response=await page.request.post(base+'/api/records',{data:{inventory_number:'LP-88551',artist:'QR Artist',title:'QR Album'}});assert(response.ok());id=(await response.json()).id;
  await page.goto(base+'/#record/'+id);await page.locator('#show-qr').click();await page.locator('#qr-preview svg').waitFor();const link=base+'/#record/'+id;assert.equal(await decode(page.locator('#qr-preview')),link);
  for(const theme of ['gallery','studio','listening']){await page.evaluate(theme=>document.querySelector(`button[data-theme=${theme}]`).click(),theme);assert.equal(await decode(page.locator('#qr-preview')),link);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
  const [svgDownload]=await Promise.all([page.waitForEvent('download'),page.locator('#qr-download').click()]);assert.equal(svgDownload.suggestedFilename(),'grooveshelf-LP-88551-qr.svg');const svg=fs.readFileSync(await svgDownload.path(),'utf8');assert(svg.includes('<svg'));assert(!svg.includes('<script'));
  await page.locator('#qr-origin').fill('http://user:secret@example.test');assert(await page.locator('#qr-output').isHidden());await page.getByRole('button',{name:'Generate QR code',exact:true}).click();await page.getByText('Use an HTTP or HTTPS collection address without credentials, a path, query or fragment.',{exact:true}).waitFor();
  await page.locator('#qr-origin').fill('http://grooveshelf.local:8080');await page.getByRole('button',{name:'Generate QR code',exact:true}).click();assert.equal(await decode(page.locator('#qr-preview')),'http://grooveshelf.local:8080/#record/'+id);await page.locator('#qr-close').click();await page.locator('#show-qr').click();assert.equal(await page.locator('#qr-origin').inputValue(),'http://grooveshelf.local:8080');await page.locator('#qr-origin').fill(base);await page.getByRole('button',{name:'Generate QR code',exact:true}).click();await page.locator('#qr-close').click();await page.locator('#close-details').click();await page.locator('#details').waitFor({state:'hidden'});
  // Decode the print preview at desktop resolution; a mobile A4 thumbnail
  // can rasterize a module below two pixels and is not the printed label.
  await page.setViewportSize({width:1280,height:900});
  await openNavigation(page);await page.locator('#labels-open').click();await page.getByText('0 selected · 1 visible').waitFor();assert(!await page.locator('#labels-qr').isChecked());await page.locator('#labels-select').click();await page.locator('#labels-qr').check();assert.equal(await page.locator('#labels-form [name=qr_origin]').inputValue(),base);await page.locator('#labels-form [name=skip]').fill('1');await page.getByRole('button',{name:'Build preview'}).click();await page.locator('#labels-output').waitFor({state:'visible'});const preview=page.frameLocator('#labels-preview');await preview.locator('.qr-label svg').waitFor();assert.equal(await preview.locator('.label').count(),2);assert.equal(await preview.locator('.label').first().textContent(),'');assert.equal(await decode(preview.locator('.qr-label svg')),link);
  const [htmlDownload]=await Promise.all([page.waitForEvent('download'),page.locator('#labels-download').click()]);const html=fs.readFileSync(await htmlDownload.path(),'utf8');assert(html.includes('<svg'));assert(!html.includes('<script'));assert(!html.includes('<img'));assert(!html.includes('<link'));assert(html.includes('LP-88551'));const standalone=await context.newPage();await standalone.setContent(html);assert.equal(await decode(standalone.locator('.qr-label svg')),link);await standalone.close();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/grooveshelf-qr-labels-mobile.png'});
  await page.locator('#labels-qr').uncheck();assert(await page.locator('#labels-output').isHidden());await page.getByRole('button',{name:'Build preview'}).click();await preview.getByText('LP-88551',{exact:true}).waitFor();assert.equal(await preview.locator('svg').count(),0);await page.locator('#labels-close').click();
  await page.request.put(base+'/api/records/'+id,{data:{inventory_number:'LP-88552',artist:'QR Artist',title:'QR Album'}});await page.goto(link);await page.locator('#detail-overview').getByText('LP-88552 · LP',{exact:false}).waitFor();assert.equal((await(await page.request.get(base+'/api/records/'+id)).json()).play_count,0);assert.equal((await(await page.request.get(base+'/api/records/'+id)).json()).nfc_uid,null);
  await page.request.delete(base+'/api/records/'+id);await page.goto(link);await page.reload();await page.getByText('Record not found',{exact:false}).waitFor();await page.locator('#search').fill('deleted record');await page.waitForResponse(response=>response.url().includes('/api/records?q=deleted')&&response.status()===200);assert.equal(await page.locator('#message').textContent(),'Record not found');assert.deepEqual(external,[]);assert.deepEqual(errors,[]);console.log('QR passed: independent decoding, SVG/standalone labels, safe origin, remembered address, renumbering, missing records, no plays/NFC changes, themes and mobile layout.');
 }finally{if(id)await page.request.delete(base+'/api/records/'+id);await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
