const {openNavigation}=require('./navigation.cjs');
const assert=require('node:assert/strict');const {chromium}=require('playwright');const base=process.env.GROOVESHELF_TEST_URL||'http://127.0.0.1:8080';
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});const ids=[];let playId;const errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto(base);await openNavigation(page);await page.locator('#stats-open').click();await page.getByText('0 recorded plays in this date range.').waitFor();await page.getByText('No monthly totals yet.').waitFor();await page.locator('#stats-close').click();
 for(const [inventory_number,title] of [['LP-88551','Frequently played'],['LP-88552','Never played album']]){const response=await page.request.post(base+'/api/records',{data:{inventory_number,artist:'Statistics Artist',title}});assert(response.ok());ids.push((await response.json()).id);}
 const play=await(await page.request.post(`${base}/api/records/${ids[0]}/plays`,{data:{played_at:'2026-01-31T23:30:00Z'}})).json();playId=play.id;
 await openNavigation(page);await page.locator('#stats-open').click();await page.getByText('1 recorded play in this date range.').waitFor();assert.equal(await page.locator('#stats-result tbody tr').first().locator('td').first().textContent(),'2026-02');
 await page.locator('#stats-start').fill('2026-02-01');await page.locator('#stats-end').fill('2026-02-28');await page.locator('#stats-apply').click();await page.getByText('1 recorded play in this date range.').waitFor();await page.screenshot({path:'/tmp/grooveshelf-stats-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#stats-result').getByRole('button',{name:/LP-88552/}).click();await page.locator('#details').waitFor({state:'visible'});await page.getByRole('button',{name:'Close details'}).click();
 await page.request.put(`${base}/api/plays/${play.id}`,{data:{played_at:'2026-01-01T12:00:00Z'}});await openNavigation(page);await page.locator('#stats-open').click();await page.getByText('0 recorded plays in this date range.').waitFor();await page.locator('#stats-clear').click();await page.getByText('1 recorded play in this date range.').waitFor();assert.equal(await page.locator('#stats-start').inputValue(),'');
 await page.locator('#stats-start').fill('2026-02-01');await page.locator('#stats-end').fill('2026-01-01');await page.locator('#stats-apply').click();await page.getByText('The start date must be on or before the end date.').waitFor();
 assert.deepEqual(errors,[]);console.log('Statistics browser flow passed: empty history, monthly grouping, date range, lifetime never-played, detail navigation, corrections, invalid range and mobile layout.');
 }finally{if(playId)await page.request.delete(base+'/api/plays/'+playId);for(const id of ids)await page.request.delete(base+'/api/records/'+id);await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
